import {
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  OneToMany,
} from 'typeorm';
import { ShoppingListItem } from './shopping-list-item.entity';

export type ShoppingListStatus =
  | 'pending' // 待购买
  | 'partial' // 部分购买
  | 'completed'; // 已全部购买

@Entity({ name: 'shopping_lists' })
export class ShoppingList {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ length: 128 })
  name!: string;

  @Column({ type: 'text', nullable: true })
  remarks!: string | null;

  @Column({ type: 'varchar', length: 16, default: 'pending' })
  status!: ShoppingListStatus;

  @Column({ type: 'boolean', default: false })
  autoGenerated!: boolean;

  @OneToMany(() => ShoppingListItem, (item) => item.shoppingList, {
    cascade: true,
    eager: true,
  })
  items!: ShoppingListItem[];

  @CreateDateColumn({ name: 'created_at' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt!: Date;
}
