import { BadRequestException, NotFoundException } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { getRepositoryToken } from '@nestjs/typeorm';
import { Item } from '../items/entities/item.entity';
import { ShoppingListsService } from './shopping-lists.service';
import { ShoppingList } from './entities/shopping-list.entity';
import { ShoppingListItem } from './entities/shopping-list-item.entity';

type MockRepo = Partial<
  Record<
    'find' | 'findOne' | 'create' | 'save' | 'remove' | 'delete',
    jest.Mock
  >
>;

describe('ShoppingListsService', () => {
  let service: ShoppingListsService;
  let shoppingListRepo: MockRepo;
  let shoppingListItemRepo: MockRepo;
  let itemsRepo: MockRepo;

  const item: Item = {
    id: 'item-1',
    name: '牛奶',
    code: null,
    brand: null,
    specification: null,
    unit: '瓶',
    shelfLifeDays: null,
    imageUrl: null,
    remarks: null,
    category: { id: 'cat-1' } as unknown as Item['category'],
    defaultLocation: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: [],
  };

  beforeEach(async () => {
    const moduleRef = await Test.createTestingModule({
      providers: [
        ShoppingListsService,
        {
          provide: getRepositoryToken(ShoppingList),
          useValue: {
            find: jest.fn(),
            findOne: jest.fn(),
            create: jest.fn(),
            save: jest.fn(),
            remove: jest.fn(),
          },
        },
        {
          provide: getRepositoryToken(ShoppingListItem),
          useValue: {
            create: jest.fn(),
            save: jest.fn(),
            delete: jest.fn(),
          },
        },
        {
          provide: getRepositoryToken(Item),
          useValue: {
            find: jest.fn(),
          },
        },
      ],
    }).compile();

    service = moduleRef.get(ShoppingListsService);
    shoppingListRepo = moduleRef.get(getRepositoryToken(ShoppingList));
    shoppingListItemRepo = moduleRef.get(getRepositoryToken(ShoppingListItem));
    itemsRepo = moduleRef.get(getRepositoryToken(Item));
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should create shopping list with items', async () => {
    (itemsRepo.find as jest.Mock).mockResolvedValue([item]);
    const savedList: ShoppingList = {
      id: 'list-1',
      name: '周末采购',
      remarks: null,
      status: 'pending',
      autoGenerated: false,
      items: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    (shoppingListRepo.create as jest.Mock).mockReturnValue(savedList);
    (shoppingListRepo.save as jest.Mock).mockResolvedValue(savedList);

    const result = await service.create({
      name: '周末采购',
      items: [{ itemId: item.id, quantity: 2 }],
    });

    expect(result).toBe(savedList);
    expect(itemsRepo.find).toHaveBeenCalled();
    expect(shoppingListItemRepo.create).toHaveBeenCalledTimes(1);
  });

  it('should throw when item missing', async () => {
    (itemsRepo.find as jest.Mock).mockResolvedValue([]);
    await expect(
      service.create({
        name: '清单',
        items: [{ itemId: 'missing', quantity: 1 }],
      }),
    ).rejects.toThrow(BadRequestException);
  });

  it('should mark item status and update list status', async () => {
    const list: ShoppingList = {
      id: 'list-1',
      name: '清单',
      remarks: null,
      status: 'pending',
      autoGenerated: false,
      items: [
        {
          id: 'entry-1',
          shoppingList: { id: 'list-1' } as unknown as ShoppingList,
          item,
          quantity: 1,
          status: 'pending',
          remarks: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    (shoppingListRepo.findOne as jest.Mock).mockResolvedValueOnce(list);
    (shoppingListItemRepo.save as jest.Mock).mockResolvedValue(undefined);
    (shoppingListRepo.save as jest.Mock).mockResolvedValue(undefined);
    (shoppingListRepo.findOne as jest.Mock).mockResolvedValueOnce({
      ...list,
      status: 'completed',
      items: [{ ...list.items[0], status: 'purchased' }],
    });

    const result = await service.markItemStatus(list.id, item.id, 'purchased');

    expect(result.status).toBe('completed');
  });

  it('should throw if list not found', async () => {
    (shoppingListRepo.findOne as jest.Mock).mockResolvedValue(null);
    await expect(service.findOne('missing')).rejects.toThrow(NotFoundException);
  });
});
