import { Controller, Logger } from '@nestjs/common';
import { EventPattern, Payload } from '@nestjs/microservices';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ShoppingListsService } from './shopping-lists.service';
import { ShoppingList } from './entities/shopping-list.entity';
import { ShoppingListItem } from './entities/shopping-list-item.entity';
import { Item } from '../items/entities/item.entity';
import type { ShoppingListEvent } from '../notifications/shopping-list-producer.service';

@Controller()
export class ShoppingListConsumerService {
  private readonly logger = new Logger(ShoppingListConsumerService.name);

  constructor(
    private readonly shoppingListsService: ShoppingListsService,
    @InjectRepository(ShoppingList)
    private readonly shoppingListRepo: Repository<ShoppingList>,
    @InjectRepository(ShoppingListItem)
    private readonly shoppingListItemRepo: Repository<ShoppingListItem>,
    @InjectRepository(Item)
    private readonly itemsRepo: Repository<Item>,
  ) {}

  @EventPattern('shopping-lists.auto-create')
  async handleAutoCreate(@Payload() event: ShoppingListEvent): Promise<void> {
    this.logger.debug(
      `Received shopping list event for item ${event.itemId} (${event.reason})`,
    );

    const item = await this.itemsRepo.findOne({
      where: { id: event.itemId },
      relations: ['category', 'defaultLocation'],
    });
    if (!item) {
      this.logger.warn(`Item ${event.itemId} not found, skip shopping list`);
      return;
    }

    let list = await this.shoppingListRepo.findOne({
      where: {
        autoGenerated: true,
        status: 'pending',
      },
    });

    if (!list) {
      list = await this.shoppingListRepo.save(
        this.shoppingListRepo.create({
          name: `自动清单 ${new Date().toISOString().slice(0, 10)}`,
          remarks: `系统根据${event.reason === 'low_stock' ? '低库存' : '临期'}提醒自动生成`,
          status: 'pending',
          autoGenerated: true,
          items: [],
        }),
      );
    }

    const existingEntry = list.items.find(
      (entry) => entry.item.id === event.itemId,
    );

    if (existingEntry) {
      existingEntry.quantity = Number(
        (existingEntry.quantity + event.quantity).toFixed(2),
      );
      await this.shoppingListItemRepo.save(existingEntry);
    } else {
      const entry = this.shoppingListItemRepo.create({
        shoppingList: list,
        item,
        quantity: event.quantity,
        status: 'pending',
        remarks:
          event.reason === 'near_expiry' ? '临期优先购买' : '库存不足，需补货',
      });
      await this.shoppingListItemRepo.save(entry);
    }

    list = await this.shoppingListsService.findOne(list.id);
    this.logger.log(
      `Shopping list ${list.id} updated with item ${event.itemId}`,
    );
  }
}
